apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: k8s-n2p
  labels:
    app: hello
spec:
  backend:
    serviceName: helloweb-backend
    servicePort: {{ .Values.service.containerPort }}