# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/net2phone-sandbox/hello
  tag: 0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  externalPort: 8080
  containerPort: 8080
  nodePort: 31198

ingress:
  enabled: true
  #annotations: {}
  annotations:
    kubernetes.io/ingress.class: nginx
  paths: []
  hosts:
    - helloworld.local
resources:
  limits:
  requests:
    cpu: 10m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

logLevel: debug
